10_cavity: 10_cavity.cpp
	g++ 10_cavity.cpp
11_cavity_omp: 11_cavity_omp.cpp
	g++ 11_cavity_omp.cpp -fopenmp
12_cavity_acc: 12_cavity_acc.cpp
	nvc++ 12_cavity_acc.cpp -acc
13_cavity_cuda: 13_cavity_cuda.cu
	nvcc -O3 13_cavity_cuda.cu
